GET http://localhost:3001/products

###


GET http://localhost:3001/restaurants

###

GET http://localhost:3001/menus

###


POST http://localhost:3001/customers
content-type: application/json

###

POST http://localhost:3001/flight/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxMDM0MDE5NCwiZXhwIjoxNzEwMzQzNzk0fQ.cwG4wJ_iWzV4pbkiGdtfp4SWKxgw4s73coKmBVVGy6A


{
    "origin": "AJU",
    "destination": "LONDON",
    "departure": "2022-06-01T15:00:00",
    "airline": "DCN",
    "price": 200
}

###

POST http://localhost:3001/passenger/create
content-type: application/json

{
    "name": "Leonardo",
    "email": "leonardo@gmail.com"
}


###

GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNCIsInJvbGUiOiJQQVNTRU5HRVIiLCJpYXQiOjE3MTAzNDQ5MzIsImV4cCI6MTcxMDM0ODUzMn0.8YOKjmL8gHkTycLqt2tAvkvz7gjhjPVbN4Fn2iP0KMc


###

POST http://localhost:3001/user/create
content-type: application/json

{
    "name": "Maria",
    "email": "maria@gmail.com",
    "password": "12345",
    "role": "PASSENGER"
}

###

POST http://localhost:3001/auth
content-type: application/json

{
   "email": "maria@gmail.com",
    "password": "12345"
}


